export enum Permission {
  // Estudios
  VIEW_STUDY        = 'VIEW_STUDY',
  SEND_STUDY        = 'SEND_STUDY',
  DELETE_STUDY      = 'DELETE_STUDY',
  CREATE_DIAGNOSTIC = 'CREATE_DIAGNOSTIC',

  // Agenda
  VIEW_AGENDA       = 'VIEW_AGENDA',
  CREATE_CONSULT    = 'CREATE_CONSULT',
  CREATE_URGENCY    = 'CREATE_URGENCY',

  // Pacientes
  VIEW_PATIENT      = 'VIEW_PATIENT',
  CREATE_PATIENT    = 'CREATE_PATIENT',
  EDIT_PATIENT      = 'EDIT_PATIENT',
  DELETE_PATIENT    = 'DELETE_PATIENT',

  // Médicos
  VIEW_DOCTOR       = 'VIEW_DOCTOR',
  CREATE_DOCTOR     = 'CREATE_DOCTOR',
  EDIT_DOCTOR       = 'EDIT_DOCTOR',
  DELETE_DOCTOR     = 'DELETE_DOCTOR',

  // Configuración PACS
  MANAGE_PACS       = 'MANAGE_PACS',

  // Usuarios
  MANAGE_USERS      = 'MANAGE_USERS',

  // Consultorio
  MANAGE_OFFICE     = 'MANAGE_OFFICE',
}
